# 00. PyTorch Fundamentals Exercises

In [1]:
import torch

### 1. Documentation Reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

- The documentation on ``torch.Tensor``
- The documentation on ``torch.cuda``

In [2]:
# No code solution (reading)

### 2. Create a random tensor with shape (7, 7)

In [3]:
tensor = torch.rand(7, 7)
tensor

tensor([[0.9936, 0.7474, 0.9114, 0.6024, 0.2004, 0.2724, 0.8118],
        [0.4415, 0.9113, 0.2027, 0.5955, 0.5918, 0.8320, 0.8319],
        [0.2516, 0.1632, 0.1338, 0.1523, 0.7776, 0.9201, 0.8481],
        [0.1561, 0.0924, 0.4291, 0.4106, 0.0626, 0.4868, 0.6343],
        [0.7787, 0.9629, 0.5590, 0.5861, 0.4515, 0.2549, 0.2998],
        [0.0243, 0.2419, 0.3486, 0.6190, 0.0724, 0.6017, 0.4077],
        [0.3502, 0.6454, 0.5897, 0.6884, 0.2577, 0.9155, 0.6463]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor)

In [4]:
torch.mm(tensor, torch.rand(1, 7).T)

tensor([[2.1751],
        [2.5022],
        [1.8907],
        [1.3177],
        [1.8880],
        [1.4512],
        [2.3912]])

### 4. Set the random seed to 0 and do 2 & 3 over again

In [5]:
torch.manual_seed(0)
tensor = torch.rand(7, 7)
tensor

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [6]:
torch.manual_seed(0)
torch.mm(tensor, torch.rand(1, 7).T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

### 5. Speaking of random seeds, we saw how to set it with ``torch.manual_seed()`` but is there a GPU equivalent? (hint: you'll need to look into the documentation for ``torch.cuda`` for this one)

In [7]:
torch.cuda.manual_seed(0)

### 6. Create two random tensors of shape ``(2, 3)`` and send them both to the GPU (you'll need access to a GPU for this). ``Set torch.manual_seed(1234)`` when creating the tensors (this doesn't have to be the GPU random seed)

In [8]:
torch.manual_seed(1234)
t1 = torch.rand(2, 3)
t2 = torch.rand(2, 3)
t1, t2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))

In [ ]:
# Code is functional, my GPU is just old
t1 = t1.to("cuda")
t2 = t2.to("cuda")

### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors)

In [10]:
tensor = torch.mm(t1, t2.T)
tensor

tensor([[0., 0.],
        [1., 1.]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7

In [11]:
torch.max(tensor), torch.min(tensor)

(tensor(0., device='cuda:0'), tensor(0., device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7

In [12]:
torch.argmax(tensor), torch.argmin(tensor)

(tensor(0, device='cuda:0'), tensor(0, device='cuda:0'))

### 10. Make a random tensor with shape ``(1, 1, 1, 10)`` and then create a new tensor with all the ``1`` dimensions removed to be left with a tensor of shape ``(10)``. Set the seed to ``7`` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape

In [13]:
torch.manual_seed(7)
t1 = torch.rand(1, 1, 1, 10)
t2 = t1.squeeze()
t1, t2

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]))